title: "Stories by DeMers"  # Your website's title
description: "A personal website by B.A. DeMers"  # Short site description
baseurl: ""  # Leave empty for personal sites (mandatory for correct URL resolution)
url: "https://Sondra94534.github.io/storiesbydemers.github.io"  # Full URL to your website
permalink: pretty  # URL structure (pretty or date)
navigation:  # Define your site's navigation menu
  - name: "Home"
    url: "/"  # Root path
  - name: "About"
    url: "/about/"  # About page path
  - name: "Blog"
    url: "/blog/"  # Blog page path
  - name: "Contact"
    url: "/contact/"  # Contact page path
  - name: "Stories"
    url: "/stories/"  # Stories page path
